# Generated by Django 3.2.7 on 2021-09-22 16:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cohort_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='native',
            name='name',
        ),
        migrations.AddField(
            model_name='native',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='native',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='native',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='date_created',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='native',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cohort_project.cohort'),
        ),
        migrations.AlterField(
            model_name='native',
            name='date_added',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='native',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='native',
            name='scv',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.CreateModel(
            name='Thought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_created', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('native', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='cohort_project.native')),
            ],
        ),
    ]
