# Generated by Django 3.2.7 on 2021-09-23 13:46

import cohort_project.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cohort_project', '0002_auto_20210922_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='native',
            name='id',
        ),
        migrations.AlterField(
            model_name='native',
            name='scv',
            field=models.CharField(max_length=10, primary_key=cohort_project.models.get_SCV, serialize=False),
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=10)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cohort_project.native')),
            ],
        ),
    ]
